// Barrel re-export file — all imports from '@/lib/api' continue to work unchanged
export { default, getApiBaseUrl } from './client'
export { authApi } from './auth'
export type { RegisterData, LoginData, AuthResponse } from './auth'
export { leadsApi, tagsApi, customFieldsApi, documentsApi, notesApi } from './leads'
export type { LeadsQuery, CreateLeadData, UpdateLeadData, BulkUpdateData, CreateTagData, CreateCustomFieldData, CreateNoteData } from './leads'
export { campaignsApi, deliverabilityApi } from './campaigns'
export type { CampaignsQuery, CreateCampaignData, DeliverabilityStats, SuppressedContact } from './campaigns'
export { activitiesApi, tasksApi } from './tasks'
export type { ActivitiesQuery, CreateActivityData, TasksQuery, CreateTaskData } from './tasks'
export { analyticsApi } from './analytics'
export type { AnalyticsQuery } from './analytics'
export { aiApi } from './ai'
export type { InsightFilter, RecommendationFilter, EnhanceMessagePayload, SuggestActionsPayload, UploadTrainingDataPayload, ScoringConfigData } from './ai'
export { callsApi, messagesApi, templatesApi, messageTemplatesApi } from './communication'
export { workflowsApi } from './workflows'
export { settingsApi, teamsApi } from './settings'
export { appointmentsApi } from './appointments'
export type { AppointmentsQuery, CreateAppointmentData, UpdateAppointmentData, CalendarQuery, UpcomingQuery, SendReminderData } from './appointments'
export { notificationsApi, usersApi } from './notifications'
export type { Notification, NotificationsQuery } from './notifications'
export { adminApi, billingApi } from './admin'
export { segmentsApi, pipelinesApi, savedFiltersApi } from './pipelines'
export type { PipelineStage, PipelineData, SavedFilterView } from './pipelines'
export { remindersApi } from './reminders'
export type { FollowUpReminder, CreateReminderData } from './reminders'
export { exportApi, savedReportsApi, reportSchedulesApi, goalsApi } from './reports'
export { supportApi, docsApi } from './help'
